name: ffmpeg-ubuntu

on:
  push:
    paths:
      - 'src/ffmpeg/ubuntu/**'

  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: read
  security-events: write

jobs:
  build:
    uses: SlashNephy/.github/.github/workflows/docker-build.yml@master
    with:
      image-name: ghcr.io/slashnephy/ffmpeg-ubuntu
      context: src/ffmpeg/ubuntu
      build-args: |
        FFMPEG_VERSION=6.0
        NV_CODEC_HEADERS_REF=n12.0.16.0
        AMF_REF=v1.4.30
      tag-spec: |
        type=raw,6.0
