name: ffmpeg-ubuntu

on:
  push:
    paths:
      - 'src/ffmpeg/ubuntu/**'

  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: read
  security-events: write

env:
  # renovate: datasource=github-tags depName=FFmpeg/FFmpeg
  FFMPEG_VERSION: 6.0

jobs:
  build:
    uses: SlashNephy/.github/.github/workflows/docker-build.yml@master
    with:
      image-name: ghcr.io/slashnephy/ffmpeg-ubuntu
      context: src/ffmpeg/ubuntu
      image-platforms: linux/amd64,linux/arm64
      tag-spec: |
        type=raw,${{ env.FFMPEG_VERSION }}
