name: mirakurun-client

on:
  push:
    paths:
      - 'src/mirakurun-client/**'

  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: read
  security-events: write

jobs:
  build:
    uses: SlashNephy/.github/.github/workflows/docker-build.yml@master
    with:
      image-name: ghcr.io/slashnephy/mirakurun-client
      context: src/mirakurun-client
