name: recdvb

on:
  push:
    paths:
      - 'src/recdvb/**'

  workflow_dispatch:

permissions:
  contents: read
  packages: write
  actions: read
  security-events: write

jobs:
  build:
    uses: SlashNephy/.github/.github/workflows/docker-build.yml@master
    with:
      image-name: ghcr.io/slashnephy/recdvb
      context: src/recdvb
